### ISSUE TITLE
Ability to uncache and remove tracks info via API and commands

### ISSUE THREAD

**Issue by Dymeth** [FatSaw/AMusic#10]
We can load or update tracks using `AMusic#loadPack()`, but there is no ways to unload and remove track dynamically. Currently we have to delete track information from `data.yml` manually

**Comment by FatSaw** [comment]
To remove information from cache and `data.yml`.
Need to remove all files from playlist music directory and triger `AMusic#loadPack()` or `loadmusic` command with update flag.
