### ISSUE TITLE
Support for any chars in playlists names

### ISSUE THREAD

**Issue by Dymeth** [FatSaw/AMusic#7]
As said in README, `Not allowed characters in playlist name: @ / \ : ; , [ ] ( ) { } < > , $ & # * ? | ! % @ ^ \t \b \n \r \f ' " \0`
So it would be great to allow to use all of this chars in playlists titles.
It can be implemented with storing display name of playlists in `data.yml` or in exact music folders

**Comment by FatSaw** [comment]
Things sensitive to these characters are now uses Base64 encoding. Character type limitation removed.
P.s. rename ability without plugin restart not added yet.
