### ISSUE TITLE
Enchant tracks storing mechanism

### ISSUE THREAD

**Issue by Dymeth** [FatSaw/AMusic#9]
If the number of tracks is significantly increased, plugin users will encounter long data.yml saving time, as this overwrites the file completely.
It is necessary to either load playlist data from YML within each specific playlist, or abandon storing data in YML altogether and switch to dynamic loading/saving with databases (MariaDB, PostgreSQL, etc)

**Comment by FatSaw** [comment]
Added ability to initialise multiple AMusic instances.
With custom directory, external Config and Data storage.

For custom config storage added constructor with all options in `me.bomb.amusic#ConfigOptions`

For custom data storage need to extend `me.bomb.amusic.Data` and implement `me.bomb.amusic.Data#save();`, `me.bomb.amusic.Data#load();`

Playlists and sounds custom (not file) storage not implement yet.

**Comment by FatSaw** [comment]
data.yml removed. Each packed resourcepack now has own file.
